const { Octokit } = require("@octokit/rest");
require("dotenv").config();

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
const OWNER = process.env.GITHUB_OWNER;
const REPO = process.env.GITHUB_REPO;

// 1. Get issue details
async function getIssue(issueNumber) {
  const { data } = await octokit.issues.get({
    owner: OWNER,
    repo: REPO,
    issue_number: issueNumber,
  });
  return { title: data.title, body: data.body, number: data.number };
}

// 2. Get all files in the repo (recursively)
async function getRepoFiles() {
  const { data: tree } = await octokit.git.getTree({
    owner: OWNER,
    repo: REPO,
    tree_sha: "HEAD",
    recursive: "true",
  });

  const files = [];
  for (const item of tree.tree) {
    // Only grab JS/TS/Python files, skip node_modules
    if (
      item.type === "blob" &&
      !item.path.includes("node_modules") &&
      !item.path.includes(".git") &&
      (item.path.endsWith(".js") ||
        item.path.endsWith(".ts") ||
        item.path.endsWith(".py") ||
        item.path.endsWith(".md"))
    ) {
      try {
        const { data: blob } = await octokit.git.getBlob({
          owner: OWNER,
          repo: REPO,
          file_sha: item.sha,
        });
        const content = Buffer.from(blob.content, "base64").toString("utf-8");
        files.push({ path: item.path, content, sha: item.sha });
      } catch (e) {
        console.log(`Skipping ${item.path}: ${e.message}`);
      }
    }
  }
  return files;
}

// 3. Create a new branch
async function createBranch(branchName) {
  // Get the SHA of the default branch (main or master)
  const { data: ref } = await octokit.git.getRef({
    owner: OWNER,
    repo: REPO,
    ref: "heads/main",
  }).catch(() =>
    octokit.git.getRef({ owner: OWNER, repo: REPO, ref: "heads/master" })
  );

  await octokit.git.createRef({
    owner: OWNER,
    repo: REPO,
    ref: `refs/heads/${branchName}`,
    sha: ref.object.sha,
  });

  console.log(`✅ Branch created: ${branchName}`);
  return branchName;
}

// 4. Push changed files to the new branch
async function pushFiles(branchName, changedFiles) {
  for (const file of changedFiles) {
    // Get current file SHA if it exists
    let fileSha;
    try {
      const { data } = await octokit.repos.getContent({
        owner: OWNER,
        repo: REPO,
        path: file.path,
        ref: branchName,
      });
      fileSha = data.sha;
    } catch {
      fileSha = undefined; // New file
    }

    await octokit.repos.createOrUpdateFileContents({
      owner: OWNER,
      repo: REPO,
      path: file.path,
      message: `fix: update ${file.path} to address issue`,
      content: Buffer.from(file.newContent).toString("base64"),
      branch: branchName,
      sha: fileSha,
    });

    console.log(`✅ Pushed: ${file.path}`);
  }
}

// 5. Create a Pull Request
async function createPullRequest(branchName, issue, reviewFeedback) {
  const { data: pr } = await octokit.pulls.create({
    owner: OWNER,
    repo: REPO,
    title: `Fix: ${issue.title}`,
    body: `## 🤖 Auto-generated PR\n\n**Closes #${issue.number}**\n\n### Changes Made\nThis PR was automatically generated to address the issue.\n\n### Automated Review Feedback\n${reviewFeedback}\n\n---\n*Generated by Issue-to-PR Bot*`,
    head: branchName,
    base: "main",
  }).catch(() =>
    octokit.pulls.create({
      owner: OWNER,
      repo: REPO,
      title: `Fix: ${issue.title}`,
      body: `## 🤖 Auto-generated PR\n\n**Closes #${issue.number}**\n\n### Automated Review\n${reviewFeedback}`,
      head: branchName,
      base: "master",
    })
  );

  console.log(`✅ PR Created: ${pr.html_url}`);
  return pr.html_url;
}
async function getAllIssues() {
  const { data } = await octokit.issues.listForRepo({
    owner: OWNER,
    repo: REPO,
    state: "open",
    per_page: 20, // get up to 20 open issues
  });
 
  return data.map((issue) => ({
    number: issue.number,
    title: issue.title,
    body: issue.body,
    labels: issue.labels.map((l) => l.name),
    createdAt: issue.created_at,
  }));
}

module.exports = { getIssue, getRepoFiles, createBranch, pushFiles, createPullRequest, getAllIssues };
